# Generated by Django 5.2.4 on 2025-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_seller",
            field=models.BooleanField(default=True),
        ),
    ]
