# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_is_staff_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="manual_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
