# Generated by Django 5.2.4 on 2025-08-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_selleruser_delete_customuser"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0003_alter_category_options_and_more"),
        ("token_blacklist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SellerUser",
            new_name="CustomUser",
        ),
    ]
