# Generated by Django 5.2.4 on 2025-08-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_rename_selleruser_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="manual_password",
        ),
    ]
