# Generated by Django 5.2.4 on 2025-08-16 09:48

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_profile_photo"),
        ("common", "0003_alter_district_created_at_alter_district_guid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="region",
                chained_model_field="region",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.district",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="common.region",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
