# Generated by Django 5.2.4 on 2025-08-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_customuser_guid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="updated_at",
            new_name="updated_time",
        ),
    ]
