# Generated by Django 5.2.4 on 2025-08-16 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_customuser_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
