# Generated by Django 5.2.4 on 2025-07-26 11:37

import common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        validators=[common.validators.icon_extensions],
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
