# Generated by Django 5.2.4 on 2025-08-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_name_ru_category_name_uz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="updated_time",
            new_name="updated_at",
        ),
    ]
