# Generated by Django 5.2.4 on 2025-08-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_favouriteproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouriteproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to="store.ad",
            ),
        ),
        migrations.AlterField(
            model_name="favouriteproduct",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="favouriteproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "product"),
                name="unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="favouriteproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device_id__isnull", False)),
                fields=("device_id", "product"),
                name="unique_device_product",
            ),
        ),
    ]
