# Generated by Django 5.2.4 on 2025-08-16 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_rename_created_at_category_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
