# Generated by Django 5.2.4 on 2025-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_category_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
