# Generated by Django 5.2.4 on 2025-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_ad_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
