# Generated by Django 5.2.4 on 2025-08-18 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_mysearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="adphoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adphoto",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
