# Generated by Django 5.2.4 on 2025-08-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_searchcount_searchquery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="address",
        ),
    ]
