# Generated by Django 5.2 on 2025-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="content",
            new_name="content_ru",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="title",
            new_name="title_ru",
        ),
        migrations.AddField(
            model_name="page",
            name="content_uz",
            field=models.TextField(default="Kontent (UZ)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="title_uz",
            field=models.CharField(default="Sarlavha (UZ)", max_length=255),
            preserve_default=False,
        ),
    ]
