# Generated by Django 5.2.4 on 2025-08-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="district",
            old_name="updated_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="updated_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="updated_time",
            new_name="updated_at",
        ),
    ]
