# Generated by Django 5.2 on 2025-07-16 08:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_content_page_content_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(default="Kontent mavjud emas"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="guid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(default="Test title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
