# Generated by Django 5.2 on 2025-07-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_page_content_page_created_time_page_guid_page_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="page",
            name="updated_at",
        ),
    ]
