# Generated by Django 5.2.4 on 2025-08-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_district_guid_alter_page_guid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="district",
            old_name="updated_at",
            new_name="updated_time",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="updated_at",
            new_name="updated_time",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="updated_at",
            new_name="updated_time",
        ),
    ]
