# Generated by Django 5.2 on 2025-07-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_region_setting_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="working_hours_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="working_hours_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
