# Generated by Django 5.2 on 2025-07-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_district_name_ru_district_name_uz_region_name_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="guid",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="updated_time",
        ),
    ]
